version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    groups:
      astro:
        patterns:
          - "astro"
          - "@astrojs/*"
      preact:
        patterns:
          - "preact"
          - "@preact/*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
      prettier:
        patterns:
          - "prettier"
          - "prettier-*"
